// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7SCfxQrHBZtnElbqM1Lny95JWDE8mE6M',
    appId: '1:13571525924:web:3b1eea24eb9ef363a637b1',
    messagingSenderId: '13571525924',
    projectId: 'telegram-bot-c06c0',
    authDomain: 'telegram-bot-c06c0.firebaseapp.com',
    storageBucket: 'telegram-bot-c06c0.appspot.com',
    measurementId: 'G-VVTQ7HR4PQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ5RowIQ30y4GasY6KTo0miig8qg8-8gw',
    appId: '1:13571525924:android:7e528e78137b69e0a637b1',
    messagingSenderId: '13571525924',
    projectId: 'telegram-bot-c06c0',
    storageBucket: 'telegram-bot-c06c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZGfWmxakzcv6LfU_Yc9QEvvMpskArI9Q',
    appId: '1:13571525924:ios:b6849f7dc15c0960a637b1',
    messagingSenderId: '13571525924',
    projectId: 'telegram-bot-c06c0',
    storageBucket: 'telegram-bot-c06c0.appspot.com',
    iosBundleId: 'com.example.telegramBot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZGfWmxakzcv6LfU_Yc9QEvvMpskArI9Q',
    appId: '1:13571525924:ios:b6849f7dc15c0960a637b1',
    messagingSenderId: '13571525924',
    projectId: 'telegram-bot-c06c0',
    storageBucket: 'telegram-bot-c06c0.appspot.com',
    iosBundleId: 'com.example.telegramBot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7SCfxQrHBZtnElbqM1Lny95JWDE8mE6M',
    appId: '1:13571525924:web:b6460dbdfec1a527a637b1',
    messagingSenderId: '13571525924',
    projectId: 'telegram-bot-c06c0',
    authDomain: 'telegram-bot-c06c0.firebaseapp.com',
    storageBucket: 'telegram-bot-c06c0.appspot.com',
    measurementId: 'G-FXKDSR6ZMX',
  );
}
